### ISSUE TITLE
Use of CDN in

### ISSUE THREAD

**Issue by wilsonmar** [mmistakes/made-mistakes-images#2]
I was delighted to find that I can specify a URL for the hero image in the front-matter:

```
image:
  feature: https://cloud.githubusercontent.com/assets/300046/14580245/036e91dc-0385-11e6-984f-00cf841ce870.png
  credit: Steve Mckinzie
  creditlink: 

```
The example is from my page at http://wilsonmar.github.io/loadrunner-javascript-coding/
I can now remove such images from the github repo, plus
gain the speed boost from being in a CDN.

Thank you for the foresight you had in allowing this to happen.

BTW, I nevertheless store the original image in my Amazon Cloud account where I get unlimited space with my Amazon Prime account.
